version: '3.8'

services:
  mongodb:
    image: mongo:5
    container_name: vetclinic-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - vetclinic-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: vetclinic-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=vetuser
      - RABBITMQ_DEFAULT_PASS=vetpass123
      - RABBITMQ_DEFAULT_VHOST=vetclinic
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - vetclinic-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/vetclinic-auth
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production-12345
      - JWT_EXPIRES_IN=7d
      - RABBITMQ_URL=amqp://vetuser:vetpass123@rabbitmq:5672/vetclinic
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - vetclinic-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  client-service:
    build:
      context: .
      dockerfile: services/client-service/Dockerfile
    container_name: client-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGODB_URI=mongodb://mongodb:27017/vetclinic-clients
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production-12345
      - RABBITMQ_URL=amqp://vetuser:vetpass123@rabbitmq:5672/vetclinic
      - CLIENT_CREATED_EXCHANGE=client_events
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - vetclinic-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  patient-service:
    build:
      context: .
      dockerfile: services/patient-service/Dockerfile
    container_name: patient-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - MONGODB_URI=mongodb://mongodb:27017/vetclinic-patients
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production-12345
      - RABBITMQ_URL=amqp://vetuser:vetpass123@rabbitmq:5672/vetclinic
      - CLIENT_CREATED_QUEUE=client_created_queue
      - CLIENT_CREATED_EXCHANGE=client_events
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - vetclinic-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  appointment-service:
    build:
      context: .
      dockerfile: services/appointment-service/Dockerfile
    container_name: appointment-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - PORT=3004
      - MONGODB_URI=mongodb://mongodb:27017/vetclinic-appointments
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production-12345
      - RABBITMQ_URL=amqp://vetuser:vetpass123@rabbitmq:5672/vetclinic
      - APPOINTMENT_EVENTS_EXCHANGE=appointment_events
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - vetclinic-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  medical-record-service:
    build:
      context: .  
      dockerfile: services/medical-record-service/Dockerfile
    container_name: medical-record-service
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
      - PORT=3006
      - MONGODB_URI=mongodb://mongodb:27017/vetclinic-medical-records
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production-12345
      - RABBITMQ_URL=amqp://vetuser:vetpass123@rabbitmq:5672/vetclinic
      - MEDICAL_RECORD_EVENTS_EXCHANGE=medical_record_events
      - APPOINTMENT_EVENTS_EXCHANGE=appointment_events
      - PATIENT_EVENTS_EXCHANGE=patient_events
      - CLIENT_EVENTS_EXCHANGE=client_events
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      patient-service:
        condition: service_healthy
      appointment-service:
        condition: service_healthy
    networks:
      - vetclinic-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3006/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  billing-service:
    build:
      context: .
      dockerfile: services/billing-service/Dockerfile
    container_name: billing-service
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - PORT=3005
      - MONGODB_URI=mongodb://mongodb:27017/vetclinic-billing
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production-12345
      - RABBITMQ_URL=amqp://vetuser:vetpass123@rabbitmq:5672/vetclinic
      - BILLING_EVENTS_EXCHANGE=billing_events
      - APPOINTMENT_EVENTS_EXCHANGE=appointment_events
      - MEDICAL_RECORD_EVENTS_EXCHANGE=medical_record_events
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      medical-record-service:
        condition: service_healthy
      appointment-service:
        condition: service_healthy
    networks:
      - vetclinic-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production-12345
      - AUTH_SERVICE_URL=http://auth-service:3001
      - CLIENT_SERVICE_URL=http://client-service:3002
      - PATIENT_SERVICE_URL=http://patient-service:3003
      - APPOINTMENT_SERVICE_URL=http://appointment-service:3004
      - BILLING_SERVICE_URL=http://billing-service:3005
      - MEDICAL_RECORD_SERVICE_URL=http://medical-record-service:3006
      - RABBITMQ_URL=amqp://vetuser:vetpass123@rabbitmq:5672/vetclinic
    depends_on:
      auth-service:
        condition: service_healthy
      client-service:
        condition: service_healthy
      patient-service:
        condition: service_healthy
      appointment-service:
        condition: service_healthy
      billing-service:
        condition: service_healthy
      medical-record-service:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - vetclinic-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  vetclinic-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16